
package vista;

import clases.Alquileres;
import datos.GestionDatos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Graciela_Hanna_Fiorella
 */
public class DlgAlquileres extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgAlquileres.class.getName());

    private ArrayList<Alquileres> listaAlquiler;
    private DefaultTableModel model;
    private GestionDatos gestion;


    /**
     * Creates new form DlgPropietario1
     */
    public DlgAlquileres(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }


    public DlgAlquileres(java.awt.Frame parent, boolean modal,
            ArrayList<Alquileres> listaAlquiler) {
        super(parent, modal);
        initComponents();
        this.listaAlquiler = listaAlquiler;
    }

    /**
     * Crea el diálogo utilizando la única instancia de {@link GestionDatos}
     * compartida por la aplicación. Es el constructor utilizado por
     * {@code FramePrincipal}.
     *
     * @param parent ventana padre del diálogo.
     * @param modal indica si el diálogo es modal.
     * @param gestion instancia compartida de GestionDatos.
     */
    public DlgAlquileres(java.awt.Frame parent, boolean modal, GestionDatos gestion) {
        super(parent, modal);
        initComponents();
        this.gestion = gestion;
        cargarTabla();
    }

     public  ArrayList<Alquileres> getListaAlquiler() {
        return listaAlquiler;
    }

    /**
     * Carga en {@code tblInfo} los alquileres existentes en GestionDatos.
     */
    private void cargarTabla() {
        String[] columnas = {"Núm. Alquiler", "Fecha Contrato", "Meses", "Adultos", "Niños",
            "Depósito", "Precio Alquiler", "% Increm. Anual", "Inquilino", "Vivienda", "Estado"};
        ArrayList<Alquileres> alquileres = gestion.obtenerAlquileres();
        Object[][] datos = new Object[alquileres.size()][columnas.length];
        for (int fila = 0; fila < alquileres.size(); fila++) {
            Alquileres a = alquileres.get(fila);
            datos[fila][0] = a.getNumAlquiler();
            datos[fila][1] = a.getFechContrato();
            datos[fila][2] = a.getCantMeses();
            datos[fila][3] = a.getNumAdultos();
            datos[fila][4] = a.getNumNinos();
            datos[fila][5] = a.getDepositoGarantia();
            datos[fila][6] = a.getPrecioAlquiler();
            datos[fila][7] = a.getPorcIncremAnual();
            datos[fila][8] = a.getInquilino() == null ? "" : a.getInquilino().getNomInqui();
            datos[fila][9] = a.getVivienda() == null ? "" : a.getVivienda().getDescripcion();
            datos[fila][10] = a.getEstado();
        }
        model = new DefaultTableModel(datos, columnas);
        tblInfo.setModel(model);
    }

    /**
     * Muestra en {@code tblInfo} únicamente el alquiler recibido.
     */
    private void mostrarAlquiler(Alquileres a) {
        String[] columnas = {"Núm. Alquiler", "Fecha Contrato", "Meses", "Adultos", "Niños",
            "Depósito", "Precio Alquiler", "% Increm. Anual", "Inquilino", "Vivienda", "Estado"};
        Object[][] datos = new Object[1][columnas.length];
        datos[0][0] = a.getNumAlquiler();
        datos[0][1] = a.getFechContrato();
        datos[0][2] = a.getCantMeses();
        datos[0][3] = a.getNumAdultos();
        datos[0][4] = a.getNumNinos();
        datos[0][5] = a.getDepositoGarantia();
        datos[0][6] = a.getPrecioAlquiler();
        datos[0][7] = a.getPorcIncremAnual();
        datos[0][8] = a.getInquilino() == null ? "" : a.getInquilino().getNomInqui();
        datos[0][9] = a.getVivienda() == null ? "" : a.getVivienda().getDescripcion();
        datos[0][10] = a.getEstado();
        model = new DefaultTableModel(datos, columnas);
        tblInfo.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("BUSCAR");

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnInsertar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregate.png"))); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editate.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminaaar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnInsertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (tblInfo.getSelectedRowCount() == 1){
            int resp = JOptionPane.showConfirmDialog(this, "¿Desea borrar el Objeto seleccionado?");

            if (resp == 0){  //El usuario desea borrar
                int fila = tblInfo.getSelectedRow();
                int numAlquiler = ((Number) tblInfo.getValueAt(fila, 0)).intValue();
                boolean eliminado = gestion.eliminarAlquiler(numAlquiler);
                if (eliminado) {
                    JOptionPane.showMessageDialog(this, "Alquiler eliminado correctamente.");
                    cargarTabla();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar: el registro no existe o tiene datos asociados.");
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un alquiler.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * Busca un alquiler por número a partir del texto ingresado en
     * {@code txtBuscar} y muestra únicamente ese registro en la tabla.
     * Si el campo está vacío, vuelve a mostrar todos los registros.
     */
    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {
        String texto = txtBuscar.getText().trim();

        if (texto.isEmpty()) {
            cargarTabla();
            return;
        }

        int numAlquiler;
        try {
            numAlquiler = Integer.parseInt(texto);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El número de alquiler debe ser numérico.");
            return;
        }

        Alquileres encontrado = gestion.buscarAlquiler(numAlquiler);
        if (encontrado == null) {
            JOptionPane.showMessageDialog(this, "No se encontró ningún alquiler con ese número.");
        } else {
            mostrarAlquiler(encontrado);
        }
    }

    /**
     * Toma la fila seleccionada de {@code tblInfo}, obtiene el número de su
     * columna 0 y busca el alquiler mediante
     * {@code gestion.buscarAlquiler(...)}; si existe, abre
     * {@link FrmNuevoAlquiler} en modo edición precargado con sus datos.
     */
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {
        if (tblInfo.getSelectedRowCount() != 1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un alquiler de la tabla para editar.");
            return;
        }
        int fila = tblInfo.getSelectedRow();
        int numAlquiler = ((Number) tblInfo.getValueAt(fila, 0)).intValue();
        Alquileres encontrado = gestion.buscarAlquiler(numAlquiler);
        if (encontrado == null) {
            JOptionPane.showMessageDialog(this, "El alquiler seleccionado ya no existe.");
            return;
        }
        FrmNuevoAlquiler frm = new FrmNuevoAlquiler(null, true, gestion, encontrado);
        frm.setVisible(true);
        cargarTabla();
    }

    /**
     * Abre {@link FrmNuevoAlquiler} para insertar un nuevo alquiler y,
     * al cerrarse, refresca la tabla con los datos actuales de GestionDatos.
     */
    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {
        FrmNuevoAlquiler frm = new FrmNuevoAlquiler(null, true, gestion);
        frm.setVisible(true);
        cargarTabla();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgAlquileres dialog = new DlgAlquileres(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInfo;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
