/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import clases.Mensualidades;
import datos.GestionDatos;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 * Ventana para consultar el reporte y detalle del cobro de mensualidades.
 * @author Graciela_Hanna_Fiorella
 */
public class DlgInfoMensualidad extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgInfoMensualidad.class.getName());

    private GestionDatos gestion;

    /**
     * Creates new form DlgInfoMensualidad
     */
    public DlgInfoMensualidad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Crea el diálogo utilizando la única instancia de {@link GestionDatos}
     * compartida por la aplicación, para que en una fase posterior pueda
     * consultar los datos reales del reporte. En esta fase no se implementa
     * ninguna lógica de consulta ni de cálculo.
     *
     * @param parent ventana padre del diálogo.
     * @param modal indica si el diálogo es modal.
     * @param gestion instancia compartida de GestionDatos.
     */
    public DlgInfoMensualidad(java.awt.Frame parent, boolean modal, GestionDatos gestion) {
        super(parent, modal);
        initComponents();
        this.gestion = gestion;
    }

    /**
     * Crea el diálogo mostrando el detalle real de la mensualidad recibida,
     * consultada previamente mediante la selección de una fila en
     * {@link DlgGestionMensualidades}. Solo consulta y muestra los datos; no
     * modifica ni elimina la mensualidad recibida.
     *
     * @param parent ventana padre del diálogo.
     * @param modal indica si el diálogo es modal.
     * @param gestion instancia compartida de GestionDatos.
     * @param mensualidad mensualidad real a mostrar.
     */
    public DlgInfoMensualidad(java.awt.Frame parent, boolean modal, GestionDatos gestion, Mensualidades mensualidad) {
        super(parent, modal);
        initComponents();
        this.gestion = gestion;

        jLabel1.setText("Consulta Para el Periodo: " + mensualidad.getMesCobro() + "/" + mensualidad.getAnioActual());
        jLabel2.setText("Total Cobrado en el Mes: " + mensualidad.getMontoMes());

        String[] columnas = {"Consecutivo", "Num Alquiler", "Inquilino", "Monto", "Estado"};
        Object[][] datos = new Object[][]{{
            mensualidad.getConsecutivo(),
            mensualidad.getNumAlquiler(),
            mensualidad.getNomInquilino(),
            mensualidad.getMontoMes(),
            mensualidad.getEstado()
        }};
        tblInformacion.setModel(new DefaultTableModel(datos, columnas));
    }

    public DlgInfoMensualidad(java.awt.Frame parent, boolean modal, GestionDatos gestion,
            ArrayList<Mensualidades> mensualidades, int mes, int anio) {
        super(parent, modal);
        initComponents();
        this.gestion = gestion;

        jLabel1.setText("Consulta Para el Periodo: " + mes + "/" + anio);

        String[] columnas = {"Consecutivo", "Num Alquiler", "Inquilino", "Monto", "Estado"};
        Object[][] datos = new Object[mensualidades.size()][columnas.length];
        double totalCobrado = 0;
        for (int fila = 0; fila < mensualidades.size(); fila++) {
            Mensualidades m = mensualidades.get(fila);
            datos[fila][0] = m.getConsecutivo();
            datos[fila][1] = m.getNumAlquiler();
            datos[fila][2] = m.getNomInquilino();
            datos[fila][3] = m.getMontoMes();
            datos[fila][4] = m.getEstado();
            totalCobrado += m.getMontoMes();
        }
        tblInformacion.setModel(new DefaultTableModel(datos, columnas));
        jLabel2.setText("Total Cobrado en el Mes: " + totalCobrado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInformacion = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte De Mensualidades Consultadas");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Consulta Para el Periodo: ");

        tblInformacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Consecutivo", "Num Alquiler", "Inquilino", "Monto", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblInformacion);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Total Cobrado en el Mes: ");

        btnCerrar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgInfoMensualidad dialog = new DlgInfoMensualidad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInformacion;
    // End of variables declaration//GEN-END:variables
}
