
package vista;

import clases.Propietario;
import datos.GestionDatos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Ventana para la gestión de propietarios (consultar, buscar, agregar, editar y eliminar).
 * @author Graciela_Hanna_Fiorella
 */
public class DlgPropietario1 extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgPropietario1.class.getName());

    private ArrayList<Propietario> listaPropietario;
    private DefaultTableModel model;
    private GestionDatos gestion;


    /**
     * Creates new form DlgPropietario1
     */
    public DlgPropietario1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }


    public DlgPropietario1(java.awt.Frame parent, boolean modal,
            ArrayList<Propietario> listaPropietario) {
        super(parent, modal);
        initComponents();
        this.listaPropietario = listaPropietario;
    }

    /**
     * Crea el diálogo utilizando la única instancia de {@link GestionDatos}
     * compartida por la aplicación. Es el constructor utilizado por
     * {@code FramePrincipal}.
     *
     * @param parent ventana padre del diálogo.
     * @param modal indica si el diálogo es modal.
     * @param gestion instancia compartida de GestionDatos.
     */
    public DlgPropietario1(java.awt.Frame parent, boolean modal, GestionDatos gestion) {
        super(parent, modal);
        initComponents();
        this.gestion = gestion;
        cargarTabla();
    }

     public  ArrayList<Propietario> getListaPropietario() {
        return listaPropietario;
    }

    /**
     * Carga en {@code tblInfo} todos los propietarios existentes en
     * GestionDatos.
     */
    private void cargarTabla() {
        mostrarEnTabla(gestion.obtenerPropietarios());
    }

    /**
     * Construye el modelo de {@code tblInfo} a partir de la lista de
     * propietarios recibida. Se usa tanto para mostrar el listado completo
     * como para mostrar únicamente el resultado de una búsqueda.
     *
     * @param propietarios propietarios a mostrar en la tabla.
     */
    private void mostrarEnTabla(ArrayList<Propietario> propietarios) {
        String[] columnas = {"Cédula", "Nombre", "Género", "Dirección", "Teléfono", "Email"};
        Object[][] datos = new Object[propietarios.size()][columnas.length];
        for (int fila = 0; fila < propietarios.size(); fila++) {
            Propietario p = propietarios.get(fila);
            datos[fila][0] = p.getCedPropiet();
            datos[fila][1] = p.getNomPropiet();
            datos[fila][2] = p.getGenero();
            datos[fila][3] = p.getDireccion();
            datos[fila][4] = p.getTelefono();
            datos[fila][5] = p.getEmail();
        }
        model = new DefaultTableModel(datos, columnas);
        tblInfo.setModel(model);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("BUSCAR");

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnInsertar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregate.png"))); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editate.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminaaar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInsertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (tblInfo.getSelectedRowCount() == 1){
            int resp = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el propietario seleccionado?");

            if (resp == 0){  //El usuario desea borrar
                int fila = tblInfo.getSelectedRow();
                int cedula = ((Number) tblInfo.getValueAt(fila, 0)).intValue();
                boolean eliminado = gestion.eliminarPropietario(cedula);
                if (eliminado) {
                    JOptionPane.showMessageDialog(this, "Propietario eliminado correctamente.");
                    cargarTabla();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar: el propietario no existe o tiene viviendas asociadas.");
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un propietario de la tabla para eliminar.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * Busca (al presionar Enter en {@code txtBuscar}) el propietario cuya
     * cédula se ingresó, mediante {@code gestion.buscarPropietario(...)}, y
     * filtra {@code tblInfo} para mostrar únicamente ese resultado. Si el
     * campo está vacío, restaura el listado completo. Es independiente del
     * botón Editar, que trabaja sobre la fila seleccionada.
     */
    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {
        String texto = txtBuscar.getText().trim();
        if (texto.isEmpty()) {
            cargarTabla();
            return;
        }
        int cedula;
        try {
            cedula = Integer.parseInt(texto);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "La cédula del propietario debe ser numérica.");
            return;
        }
        Propietario encontrado = gestion.buscarPropietario(cedula);
        ArrayList<Propietario> resultado = new ArrayList<>();
        if (encontrado != null) {
            resultado.add(encontrado);
            mostrarEnTabla(resultado);
        } else {
            mostrarEnTabla(resultado);
            JOptionPane.showMessageDialog(this, "No se encontró ningún propietario con esa cédula.");
        }
        
         txtBuscar.setText("");
    }

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        FrmNuevoPropietario frm = new FrmNuevoPropietario(null, true, gestion);
        frm.setVisible(true);
        cargarTabla();
    }//GEN-LAST:event_btnInsertarActionPerformed

    /**
     * Toma la fila seleccionada de {@code tblInfo}, obtiene la cédula de su
     * columna 0 y busca el propietario mediante
     * {@code gestion.buscarPropietario(...)}; si existe, abre el formulario
     * de edición precargado con sus datos. No utiliza {@code txtBuscar}, que
     * es independiente de esta operación.
     */
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblInfo.getSelectedRowCount() != 1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un propietario de la tabla para editar.");
            return;
        }
        int fila = tblInfo.getSelectedRow();
        int cedula = ((Number) tblInfo.getValueAt(fila, 0)).intValue();
        Propietario encontrado = gestion.buscarPropietario(cedula);
        if (encontrado == null) {
            JOptionPane.showMessageDialog(this, "El propietario seleccionado ya no existe.");
            return;
        }
        FrmNuevoPropietario frm = new FrmNuevoPropietario(null, true, gestion, encontrado);
        frm.setVisible(true);
        cargarTabla();
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgPropietario1 dialog = new DlgPropietario1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInfo;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
