package vista;

import datos.GestionDatos;

/**
 * Ventana principal tipo menú de inicio para acceder a todos los módulos del sistema.
 * @author Graciela_Hanna_Fiorella
 */
public class FramePrincipal extends javax.swing.JFrame {

    private GestionDatos gestion = new GestionDatos();

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPropietario = new javax.swing.JButton();
        btnViviendas = new javax.swing.JButton();
        btnInquilinos = new javax.swing.JButton();
        btnAlquileres = new javax.swing.JButton();
        btnMensualidades = new javax.swing.JButton();
        btnGanancias = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mniPropietario = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniPropietarios = new javax.swing.JMenuItem();
        mniViviendas = new javax.swing.JMenuItem();
        mniInquilinos = new javax.swing.JMenuItem();
        mniAlquileres = new javax.swing.JMenuItem();
        mniMensualidades = new javax.swing.JMenuItem();
        mniGanancias = new javax.swing.JMenuItem();
        mniSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Alquileres GuanaRent");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btnPropietario.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        btnPropietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/propietario.png"))); // NOI18N
        btnPropietario.setText("Propietario");
        btnPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropietarioActionPerformed(evt);
            }
        });

        btnViviendas.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        btnViviendas.setText("Viviendas");
        btnViviendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViviendasActionPerformed(evt);
            }
        });

        btnInquilinos.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        btnInquilinos.setText("Inquilinos");
        btnInquilinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInquilinosActionPerformed(evt);
            }
        });

        btnAlquileres.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        btnAlquileres.setText("Alquileres");
        btnAlquileres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlquileresActionPerformed(evt);
            }
        });

        btnMensualidades.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        btnMensualidades.setText("Mensualidades");
        btnMensualidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensualidadesActionPerformed(evt);
            }
        });

        btnGanancias.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        btnGanancias.setText("Ganancias");
        btnGanancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGananciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViviendas, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPropietario)
                    .addComponent(btnInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlquileres, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMensualidades, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViviendas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlquileres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMensualidades, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/renta2.png"))); // NOI18N

        jMenu1.setText("File");

        mniPropietarios.setText("Propietarios");
        mniPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPropietariosActionPerformed(evt);
            }
        });
        jMenu1.add(mniPropietarios);

        mniViviendas.setText("Viviendas");
        mniViviendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViviendasActionPerformed(evt);
            }
        });
        jMenu1.add(mniViviendas);

        mniInquilinos.setText("Inquilinos");
        mniInquilinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniInquilinosActionPerformed(evt);
            }
        });
        jMenu1.add(mniInquilinos);

        mniAlquileres.setText("Alquileres");
        mniAlquileres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAlquileresActionPerformed(evt);
            }
        });
        jMenu1.add(mniAlquileres);

        mniMensualidades.setText("Mensualidades");
        mniMensualidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMensualidadesActionPerformed(evt);
            }
        });
        jMenu1.add(mniMensualidades);

        mniGanancias.setText("Ganancias");
        mniGanancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGananciasActionPerformed(evt);
            }
        });
        jMenu1.add(mniGanancias);

        mniSalir.setText("Salir");
        mniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mniSalir);

        mniPropietario.add(jMenu1);

        jMenu2.setText("Edit");
        mniPropietario.add(jMenu2);

        setJMenuBar(mniPropietario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropietarioActionPerformed
        DlgPropietario1 proper = new DlgPropietario1(this, true, gestion);
        proper.setLocationRelativeTo(this);
        proper.setVisible(true);
    }//GEN-LAST:event_btnPropietarioActionPerformed

    private void btnMensualidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensualidadesActionPerformed
        DlgGestionMensualidades mensualidades = new DlgGestionMensualidades(this, false, gestion);
        mensualidades.setLocationRelativeTo(this);
        mensualidades.setVisible(true);
    }//GEN-LAST:event_btnMensualidadesActionPerformed

    private void btnViviendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViviendasActionPerformed
        DlgViviendas vivienda = new DlgViviendas(this, false, gestion);
        vivienda.setLocationRelativeTo(this);
        vivienda.setVisible(true);
    }//GEN-LAST:event_btnViviendasActionPerformed

    private void btnInquilinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInquilinosActionPerformed
        DlgInquilinos inqui = new DlgInquilinos(this, false, gestion);
        inqui.setLocationRelativeTo(this);
        inqui.setVisible(true);
    }//GEN-LAST:event_btnInquilinosActionPerformed

    private void btnAlquileresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlquileresActionPerformed
        DlgAlquileres alquiler = new DlgAlquileres(this, false, gestion);
        alquiler.setLocationRelativeTo(this);
        alquiler.setVisible(true);
    }//GEN-LAST:event_btnAlquileresActionPerformed

    private void btnGananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGananciasActionPerformed
        DlgGanancias ganancias = new DlgGanancias(this, true, gestion);
        ganancias.setLocationRelativeTo(this);
        ganancias.setVisible(true);
    }//GEN-LAST:event_btnGananciasActionPerformed

    private void mniViviendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniViviendasActionPerformed
         btnViviendasActionPerformed(evt);
    }//GEN-LAST:event_mniViviendasActionPerformed

    private void mniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniSalirActionPerformed

    private void mniPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPropietariosActionPerformed
        btnPropietarioActionPerformed(evt);
    }//GEN-LAST:event_mniPropietariosActionPerformed

    private void mniInquilinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniInquilinosActionPerformed
         btnInquilinosActionPerformed(evt);
    }//GEN-LAST:event_mniInquilinosActionPerformed

    private void mniAlquileresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAlquileresActionPerformed
         btnAlquileresActionPerformed(evt);
    }//GEN-LAST:event_mniAlquileresActionPerformed

    private void mniMensualidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMensualidadesActionPerformed
        btnMensualidadesActionPerformed(evt);
    }//GEN-LAST:event_mniMensualidadesActionPerformed

    private void mniGananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGananciasActionPerformed
       btnGananciasActionPerformed(evt);  
    }//GEN-LAST:event_mniGananciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FramePrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlquileres;
    private javax.swing.JButton btnGanancias;
    private javax.swing.JButton btnInquilinos;
    private javax.swing.JButton btnMensualidades;
    private javax.swing.JButton btnPropietario;
    private javax.swing.JButton btnViviendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mniAlquileres;
    private javax.swing.JMenuItem mniGanancias;
    private javax.swing.JMenuItem mniInquilinos;
    private javax.swing.JMenuItem mniMensualidades;
    private javax.swing.JMenuBar mniPropietario;
    private javax.swing.JMenuItem mniPropietarios;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JMenuItem mniViviendas;
    // End of variables declaration//GEN-END:variables
}
